@startuml

class Invoker {
  setCommand(ICommand)
}

interface ICommand {
  excute()
  unexcute()
}

class Command {
  excute()
  unexcute()
}

class Receiver {
  action()
}

Invoker ->"0..*" ICommand
ICommand <|-- Command
Receiver <- Command

@enduml